// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oytxonaumefjsnkpzbxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dHhvbmF1bWVmanNua3B6Ynh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDM4ODUsImV4cCI6MjA3MjU3OTg4NX0.FMHtubwkCv5E53sHsX_1KjvFxw4JcC4u5LJ1KeCaBQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});